In [1]:
# ==========================================
# PROYECTO: CLIMA Y CALIDAD DEL AIRE
# PRIMERA ETAPA: CARGA Y EXPLORACIÓN INICIAL
# ==========================================

# 1. Importar librerías
import pandas as pd
import requests
import matplotlib.pyplot as plt

# 2. Cargar dataset subiendo un nivel hacia la carpeta data
df_kaggle = pd.read_csv("../data/LA_daily_climate.csv")
df_aire = pd.read_csv("../data/LA_daily_air_quality.csv")

# 3. Mostrar las primeras filas
print("PRIMERAS FILAS DEL DATASET:")
display(df_kaggle.head())

# 4. Mostrar dimensiones
print("\nDIMENSIONES DEL DATASET:")
print("Filas:", df_kaggle.shape[0])
print("Columnas:", df_kaggle.shape[1])

# 5. Mostrar nombres de columnas
print("\nCOLUMNAS:")
print(df_kaggle.columns.tolist())

# 6. Mostrar tipos de datos
print("\nTIPOS DE DATOS:")
print(df_kaggle.dtypes)

# 7. Información general del dataset
print("\nINFORMACIÓN GENERAL:")
df_kaggle.info()

# 8. Valores faltantes
print("\nVALORES FALTANTES POR COLUMNA:")
print(df_kaggle.isnull().sum())

# 9. Registros duplicados
print("\nNÚMERO DE DUPLICADOS:")
print(df_kaggle.duplicated().sum())

# 10. Estadísticas descriptivas
print("\nESTADÍSTICAS DESCRIPTIVAS:")
display(df_kaggle.describe(include="all"))

# 11. Mostrar algunos valores únicos por columna
print("\nEJEMPLOS DE VALORES ÚNICOS:")

for columna in df_kaggle.columns:
    print(f"\n{columna}:")
    print(df_kaggle[columna].dropna().unique()[:10])

PRIMERAS FILAS DEL DATASET:

,country,city,date,latitude,longitude,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,precipitation_sum,wind_speed_10m_max,et0_fao_evapotranspiration
0,Argentina,Buenos Aires,2020-01-01 00:00:00+00:00,-34.6037,-58.3816,24.767500,19.267500,21.973753,25.061949,18.268500,22.049086,0.6,24.336640,4.160744
1,Argentina,Buenos Aires,2020-01-02 00:00:00+00:00,-34.6037,-58.3816,24.217500,18.317501,21.259167,24.995867,17.999480,20.943785,1.8,27.609911,4.593965
2,Argentina,Buenos Aires,2020-01-03 00:00:00+00:00,-34.6037,-58.3816,25.117500,20.517500,22.373750,27.362978,20.149343,22.910418,0.1,24.203140,5.876242
3,Argentina,Buenos Aires,2020-01-04 00:00:00+00:00,-34.6037,-58.3816,25.617500,20.917501,23.177916,27.975208,21.116510,24.117735,0.0,20.833395,5.913107
4,Argentina,Buenos Aires,2020-01-05 00:00:00+00:00,-34.6037,-58.3816,27.167501,20.217500,24.225832,29.682999,22.054735,25.340597,0.0,18.486622,5.996509

DIMENSIONES DEL DATASET:
Filas: 31440
Columnas: 14

COLUMNAS:
['country', 'city', 'date', 'latitude', 'longitude', 'temperature_2m_max', 'temperature_2m_min', 'temperature_2m_mean', 'apparent_temperature_max', 'apparent_temperature_min', 'apparent_temperature_mean', 'precipitation_sum', 'wind_speed_10m_max', 'et0_fao_evapotranspiration']

TIPOS DE DATOS:
country                        object
city                           object
date                           object
latitude                      float64
longitude                     float64
temperature_2m_max            float64
temperature_2m_min            float64
temperature_2m_mean           float64
apparent_temperature_max      float64
apparent_temperature_min      float64
apparent_temperature_mean     float64
precipitation_sum             float64
wind_speed_10m_max            float64
et0_fao_evapotranspiration    float64
dtype: object

INFORMACIÓN GENERAL:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31440 entries, 0 to 31439
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     31440 non-null  object
 1   city                        31440 non-null  object
 2   date                        31440 non-null  object
 3   latitude                    31440 non-null  float64
 4   longitude                   31440 non-null  float64
 5   temperature_2m_max          31440 non-null  float64
 6   temperature_2m_min          31440 non-null  float64
 7   temperature_2m_mean         31440 non-null  float64
 8   apparent_temperature_max    31440 non-null  float64
 9   apparent_temperature_min    31440 non-null  float64
 10  apparent_temperature_mean   31440 non-null  float64
 11  precipitation_sum           31440 non-null  float64
 12  wind_speed_10m_max          31440 non-null  float64
 13  et0_fao_evapotranspiration  31440 non-null  float64
dtypes: float64(11), object(3)
memory usage: 3.4+ MB

VALORES FALTANTES POR COLUMNA:
country                       0
city                          0
date                          0
latitude                      0
longitude                     0
temperature_2m_max            0
temperature_2m_min            0
temperature_2m_mean           0
apparent_temperature_max      0
apparent_temperature_min      0
apparent_temperature_mean     0
precipitation_sum             0
wind_speed_10m_max            0
et0_fao_evapotranspiration    0
dtype: int64

NÚMERO DE DUPLICADOS:
0

ESTADÍSTICAS DESCRIPTIVAS:

,country,city,date,latitude,longitude,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,precipitation_sum,wind_speed_10m_max,et0_fao_evapotranspiration
count,31440,31440,31440,31440.000000,31440.000000,31440.000000,31440.000000,31440.000000,31440.000000,31440.000000,31440.000000,31440.000000,31440.000000,31440.000000
unique,20,20,1572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Argentina,Buenos Aires,2020-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1572,1572,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,-0.351840,-74.647240,25.508726,16.637678,20.505158,26.991850,17.089077,21.282457,3.745150,17.249517,4.155612
std,NaN,NaN,NaN,19.473162,12.945977,5.542696,5.919155,5.466787,7.335015,7.889755,7.335209,7.952865,6.256400,1.345682
min,NaN,NaN,NaN,-34.901100,-99.133200,7.574000,-2.826000,3.363583,1.376739,-6.780084,0.148214,0.000000,4.024922,0.293782
25%,NaN,NaN,NaN,-16.624925,-84.627075,21.509500,11.940000,16.225583,21.186145,10.586373,14.922108,0.000000,12.574260,3.301955
50%,NaN,NaN,NaN,9.455250,-75.557450,26.246000,17.301000,21.092208,28.173572,17.677739,22.033857,0.600000,16.323528,4.075887
75%,NaN,NaN,NaN,14.212950,-66.493175,29.667501,21.527000,25.011685,32.671858,23.453022,27.175329,3.700000,20.929594,4.963958
max,NaN,NaN,NaN,23.113600,-47.921800,41.637000,30.687000,35.514080,44.652752,32.878746,37.458850,188.499980,62.876450,12.118225

EJEMPLOS DE VALORES ÚNICOS:

country:
['Argentina' 'Bolivia' 'Brazil' 'Chile' 'Colombia' 'Costa Rica' 'Cuba'
 'Dominican Republic' 'Ecuador' 'El Salvador']

city:
[' Buenos Aires' ' Sucre' ' Brasilia' ' Santiago' ' Bogota' ' San Jose'
 ' Havana' ' Santo Domingo' ' Quito' ' San Salvador']

date:
['2020-01-01 00:00:00+00:00' '2020-01-02 00:00:00+00:00'
 '2020-01-03 00:00:00+00:00' '2020-01-04 00:00:00+00:00'
 '2020-01-05 00:00:00+00:00' '2020-01-06 00:00:00+00:00'
 '2020-01-07 00:00:00+00:00' '2020-01-08 00:00:00+00:00'
 '2020-01-09 00:00:00+00:00' '2020-01-10 00:00:00+00:00']

latitude:
[-34.6037 -19.0196 -15.8267 -33.4378   4.711    9.9281  23.1136  18.4861
  -0.1807  13.6929]

longitude:
[-58.3816 -65.2619 -47.9218 -70.6504 -74.0721 -84.0907 -82.3666 -69.9312
 -78.4678 -89.2182]

temperature_2m_max:
[24.7675   24.2175   25.1175   25.6175   27.167501 26.4675   27.817501
 30.5175   28.817501 30.417501]

temperature_2m_min:
[19.2675   18.317501 20.5175   20.917501 20.2175   18.567501 15.117499
 19.4675   22.7175   20.7175  ]

temperature_2m_mean:
[21.973753 21.259167 22.37375  23.177916 24.225832 22.386251 21.613335
 24.657084 25.490417 25.119589]

apparent_temperature_max:
[25.061949 24.995867 27.362978 27.975208 29.682999 26.071087 27.52074
 29.777184 32.653004 32.97853 ]

apparent_temperature_min:
[18.2685   17.99948  20.149343 21.11651  22.054735 17.091236 12.766451
 18.071127 23.806833 21.226728]

apparent_temperature_mean:
[22.049086 20.943785 22.910418 24.117735 25.340597 21.328299 20.351297
 23.920225 27.293695 26.105042]

precipitation_sum:
[ 0.6        1.8000001  0.1        0.         9.8        1.1
  9.599999  39.700005  11.9        0.2      ]

wind_speed_10m_max:
[24.33664  27.609911 24.20314  20.833395 18.486622 31.845247 20.188908
 25.60053  16.80857  23.598541]

et0_fao_evapotranspiration:
[4.160744  4.5939646 5.876242  5.913107  5.9965086 6.566729  7.233435
 7.643038  5.669439  6.3146734]

In [2]:
print("\nPRIMERAS FILAS DEL DATASET DE CALIDAD DEL AIRE:")
display(df_aire.head())

PRIMERAS FILAS DEL DATASET DE CALIDAD DEL AIRE:

,date,city,country,latitude,longitude,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone
0,2023-01-01,Asuncion,Paraguay,-25.2637,-57.5759,10.604167,7.391667,182.583333,2.458333,0.195833,42.041667
1,2023-01-02,Asuncion,Paraguay,-25.2637,-57.5759,12.020833,8.420833,262.791667,3.512500,0.300000,27.375000
2,2023-01-03,Asuncion,Paraguay,-25.2637,-57.5759,26.008333,18.200000,460.083333,10.170833,0.479167,34.625000
3,2023-01-04,Asuncion,Paraguay,-25.2637,-57.5759,14.254167,9.945833,212.416667,3.929167,0.570833,56.333333
4,2023-01-05,Asuncion,Paraguay,-25.2637,-57.5759,32.937500,22.950000,560.625000,15.091667,0.833333,54.291667

In [3]:
print("\nDIMENSIONES DEL DATASET DE CALIDAD DEL AIRE:")
print("Filas:", df_aire.shape[0])
print("Columnas:", df_aire.shape[1])

DIMENSIONES DEL DATASET DE CALIDAD DEL AIRE:
Filas: 9520
Columnas: 11

In [4]:
df_kaggle["date"] = pd.to_datetime(df_kaggle["date"])
df_aire["date"] = pd.to_datetime(df_aire["date"])

print("\nPERIODO DEL DATASET CLIMÁTICO:")
print("Fecha inicial:", df_kaggle["date"].min())
print("Fecha final:", df_kaggle["date"].max())

print("\nPERIODO DEL DATASET DE CALIDAD DEL AIRE:")
print("Fecha inicial:", df_aire["date"].min())
print("Fecha final:", df_aire["date"].max())

PERIODO DEL DATASET CLIMÁTICO:
Fecha inicial: 2020-01-01 00:00:00+00:00
Fecha final: 2024-04-20 00:00:00+00:00

PERIODO DEL DATASET DE CALIDAD DEL AIRE:
Fecha inicial: 2023-01-01 00:00:00
Fecha final: 2024-04-20 00:00:00

In [5]:
print("\nNÚMERO DE CIUDADES EN EL DATASET CLIMÁTICO:")
print(df_kaggle["city"].nunique())

print("\nNÚMERO DE CIUDADES EN EL DATASET DE CALIDAD DEL AIRE:")
print(df_aire["city"].nunique())

NÚMERO DE CIUDADES EN EL DATASET CLIMÁTICO:
20

NÚMERO DE CIUDADES EN EL DATASET DE CALIDAD DEL AIRE:
20